# Generated by Django 5.2.4 on 2025-07-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptolog',
            name='method',
            field=models.CharField(choices=[('caesar', 'Caesar暗号'), ('base64', 'Base64'), ('random_substitution', '🎲 ランダム置換暗号'), ('morse', '🕶️ モールス信号風')], max_length=20),
        ),
    ]
