# Generated by Django 5.2.4 on 2025-07-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_cryptolog_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptolog',
            name='method',
            field=models.CharField(choices=[('caesar', 'Caesar暗号'), ('base64', 'Base64'), ('random_substitution', 'ランダム置換暗号'), ('morse', 'モールス信号風'), ('rot13', 'ROT13暗号'), ('atbash', 'Atbash暗号'), ('vigenere', 'Vigenère暗号'), ('number', '数字置換暗号'), ('binary', 'Binary暗号')], max_length=20),
        ),
    ]
